name = "lapce-nix"
version = "0.0.1"
author = "ghishadow"
display-name = "Nix"
description = "Nix lsp powered by nil"
wasm = "bin/lapce-nix.wasm"

[activation]
language = ["nix"]
workspace-contains = ["*/flake.nix"]